version: "2"
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: "homebridge"
    restart: always
    network_mode: host

    volumes:
      - /home/pi/docker/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"